# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackID', models.CharField(max_length=50)),
                ('Speed', models.CharField(max_length=50)),
                ('LatLong', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('LongLat', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
