# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_location_longlat'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(default='IMAGE', upload_to=''),
        ),
    ]
