# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.CharField(default='00:00', max_length=50),
        ),
    ]
