# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20171212_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
