# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20171212_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='location',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
