# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_auto_20171212_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('Images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image2',
        ),
        migrations.AddField(
            model_name='image',
            name='TrackID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrackImage', to='tracking.Location'),
        ),
    ]
