# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20171212_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='TrackID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracking.Location'),
        ),
    ]
