# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20171212_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='LatLong',
            new_name='latLong',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='TrackID',
            new_name='trackID',
        ),
        migrations.RemoveField(
            model_name='image',
            name='TrackID',
        ),
        migrations.AddField(
            model_name='image',
            name='trackID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='track', to='tracking.Location'),
            preserve_default=False,
        ),
    ]
