# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20171212_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='trackID',
            new_name='track',
        ),
    ]
