# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20171212_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latLong',
            new_name='latlong',
        ),
        migrations.AlterField(
            model_name='image',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tracking.location'),
        ),
    ]
