# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_auto_20171212_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latlong',
            new_name='LatLong',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='trackID',
            new_name='TrackID',
        ),
        migrations.AlterField(
            model_name='location',
            name='distance',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
